# Generated by Django 2.2.5 on 2021-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20210517_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(max_length=1000, verbose_name='Avatar'),
        ),
    ]
