# Generated by Django 2.2.5 on 2021-05-18 13:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20210518_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Admission at'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Role'),
        ),
    ]
