# Generated by Django 2.2.5 on 2021-05-19 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20210518_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_at',
            field=models.DateField(default=datetime.date(2021, 5, 19), verbose_name='Admission at'),
        ),
    ]
