# Generated by Django 2.2.5 on 2021-05-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20210519_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_at',
            field=models.DateField(default=None, verbose_name='Admission at'),
        ),
    ]
