# Generated by Django 2.2.23 on 2021-06-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20210519_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admission_at',
            field=models.DateField(default=None, null=True, verbose_name='Admission at'),
        ),
    ]
