# Generated by Django 2.2.5 on 2021-05-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='borrowed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='borrowed_at'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='renewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='renewed_at'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='returned_at'),
        ),
    ]
