# Generated by Django 2.2.5 on 2021-05-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20210520_2051'),
        ('borrow', '0002_auto_20210518_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrowed_copy', to='book.BookCopy', verbose_name='Copy'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrowed_book', to='book.Book', verbose_name='Book'),
        ),
    ]
