# Generated by Django 2.2.5 on 2021-05-20 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_auto_20210520_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finerecord',
            name='borrow_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fine', to='borrow.BorrowRecord', verbose_name='borrow_record'),
        ),
    ]
