# Generated by Django 2.2.23 on 2021-05-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_auto_20210520_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='currency_symbol',
            field=models.CharField(choices=[('THB', '฿'), ('USD', '$'), ('CNY', '￥'), ('GBP', '￡'), ('DEM', 'DM.'), ('FRP', 'FF'), ('ESP', 'Pts.'), ('JPY', 'J.')], default='฿', max_length=100, verbose_name='Symbol'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fine',
            field=models.FloatField(null=True, verbose_name='Fine'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='fined_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fined_at'),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='pay_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Paypal', 'Paypal'), ('Credit card', 'Credit card')], default='Cash', max_length=100, verbose_name='Method'),
        ),
        migrations.DeleteModel(
            name='FineRecord',
        ),
    ]
