# Generated by Django 2.2.23 on 2021-05-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_auto_20210522_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='currency_symbol',
            field=models.CharField(choices=[('THB', '฿'), ('USD', '$'), ('CNY', '￥'), ('GBP', '￡'), ('DEM', 'DM.'), ('FRP', 'FF'), ('ESP', 'Pts.'), ('JPY', 'J.')], max_length=100, null=True, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='pay_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Paypal', 'Paypal'), ('Credit card', 'Credit card')], max_length=100, null=True, verbose_name='Method'),
        ),
    ]
