# Generated by Django 2.2.23 on 2021-05-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0006_auto_20210522_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='fine',
            field=models.FloatField(default=None, null=True, verbose_name='Fine'),
        ),
    ]
