# Generated by Django 2.2.23 on 2021-05-25 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0007_auto_20210522_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='reader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='borrow_record_reader', to=settings.AUTH_USER_MODEL, verbose_name='Borrowed by'),
        ),
    ]
