# Generated by Django 2.2.5 on 2021-05-17 16:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.IntegerField(null=True, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modifier', models.IntegerField(null=True, verbose_name='modifier')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('alias', models.CharField(max_length=100, verbose_name='Alias')),
                ('nation', models.CharField(max_length=100, verbose_name='Nation')),
                ('avatar', models.CharField(max_length=1000, verbose_name='Avatar')),
                ('profile', models.TextField(max_length=10000, verbose_name='Profile')),
                ('birthday', models.DateField(default=django.utils.timezone.now, verbose_name='Birthday')),
                ('died_at', models.DateTimeField(default=None, null=True, verbose_name='Died at')),
            ],
            options={
                'db_table': 'library_author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.IntegerField(null=True, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modifier', models.IntegerField(null=True, verbose_name='modifier')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('language', models.CharField(max_length=100, verbose_name='Language')),
                ('subject', models.CharField(choices=[('A', 'General Works'), ('B', 'Philosophy (General) '), ('C', 'Auxiliary Sciences of History'), ('D', 'History'), ('E', 'History: America'), ('F', 'History: America'), ('G', 'Geography'), ('H', 'Social sciences'), ('J', 'Political Science'), ('K', 'Law'), ('L', 'Education'), ('M', 'Music'), ('N', 'Fine arts'), ('P', 'Language and Literature'), ('Q', 'Science'), ('R', 'Medicine'), ('S', 'Agriculture'), ('T', 'Technology'), ('U', 'Military Science'), ('V', 'Naval science'), ('Z', 'Library Science. Information Resources (General)')], max_length=100, verbose_name='Subject')),
                ('cover', models.FileField(max_length=200, upload_to='upload/%Y/%m/%d/', verbose_name='Cover')),
                ('description', models.TextField(max_length=10000, verbose_name='Description')),
                ('isbn_10', models.CharField(max_length=100, unique=True, verbose_name='ISBN-10')),
                ('isbn_13', models.CharField(max_length=100, unique=True, verbose_name='ISBN-13')),
                ('call_number', models.CharField(max_length=100, unique=True, verbose_name='Call number')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication Date')),
                ('toc', models.TextField(max_length=10000, verbose_name='ToC')),
                ('price', models.FloatField(verbose_name='Price')),
                ('print_length', models.IntegerField(default=1, verbose_name='Print length')),
                ('binding', models.CharField(max_length=100, verbose_name='Binding')),
                ('author', models.ManyToManyField(related_name='book_author', to='book.Author', verbose_name='Author')),
            ],
            options={
                'db_table': 'library_book',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.IntegerField(null=True, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modifier', models.IntegerField(null=True, verbose_name='modifier')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('logo', models.FileField(max_length=200, upload_to='upload/%Y/%m/%d/', verbose_name='Logo')),
                ('site', models.URLField(verbose_name='Site')),
            ],
            options={
                'db_table': 'library_publisher',
            },
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.IntegerField(null=True, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modifier', models.IntegerField(null=True, verbose_name='modifier')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('barcode', models.CharField(max_length=100, unique=True, verbose_name='Barcode')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('On-Borrowing', 'On Borrowing'), ('Staff-Only', 'Staff Only')], max_length=100, verbose_name='Status')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('media_type', models.CharField(choices=[('Text-Book', 'Text Book'), ('Printed-Text', 'Printed Text'), ('Thesis', 'Thesis'), ('Video', 'Video'), ('Sound-Recording', 'Sound Recording'), ('E-Document', 'Electronic Document'), ('Multimedia-Document', 'Multimedia Document')], max_length=100, verbose_name='Media type')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_copy_book', to='book.Book', verbose_name='Book')),
            ],
            options={
                'db_table': 'library_book_copy',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_publisher', to='book.Publisher', verbose_name='Published By'),
        ),
    ]
