# Generated by Django 2.2.23 on 2021-08-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210622_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('General Works', 'General Works'), ('Philosophy (General) ', 'Philosophy (General) '), ('Auxiliary Sciences of History', 'Auxiliary Sciences of History'), ('History', 'History'), ('History of America', 'History of America'), ('Local History of America', 'Local History of America'), ('Geography', 'Geography'), ('Social sciences', 'Social sciences'), ('Political Science', 'Political Science'), ('Law', 'Law'), ('Education', 'Education'), ('Music', 'Music'), ('Fine arts', 'Fine arts'), ('Language and Literature', 'Language and Literature'), ('Science', 'Science'), ('Medicine', 'Medicine'), ('Agriculture', 'Agriculture'), ('Technology', 'Technology'), ('Military Science', 'Military Science'), ('Naval science', 'Naval science'), ('Design', 'Design'), ('Library Science. Information Resources (General)', 'Library Science. Information Resources (General)')], max_length=100, verbose_name='Subject'),
        ),
    ]
