# Generated by Django 2.2.5 on 2021-05-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210517_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.CharField(max_length=1000, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='logo',
            field=models.CharField(max_length=1000, verbose_name='Logo'),
        ),
    ]
