# Generated by Django 2.2.5 on 2021-05-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20210518_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='died_at',
            field=models.DateField(default=None, null=True, verbose_name='Died at'),
        ),
    ]
