# Generated by Django 2.2.5 on 2021-05-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210518_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='alias',
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], default='Male', max_length=1000, verbose_name='gender'),
        ),
    ]
