# Generated by Django 2.2.5 on 2021-05-19 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210519_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=datetime.date(2021, 5, 19), verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(default=datetime.date(2021, 5, 19), verbose_name='Publication Date'),
        ),
    ]
