# Generated by Django 2.2.5 on 2021-05-20 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20210519_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nation',
            field=models.CharField(choices=[('Chinese', 'Chinese'), ('American', 'American'), ('German', 'German'), ('Japanese', 'Japanese'), ('English', 'English'), ('French', 'French'), ('Thai', 'Thai')], max_length=100, verbose_name='Nation'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('Thai', 'Thai'), ('English', 'English'), ('Chinese(Simplified)', 'Chinese(Simplified)'), ('Chinese(Traditional)', 'Chinese(Traditional)'), ('Spanish', 'Spanish'), ('German', 'German'), ('French', 'French'), ('Japanese', 'Japanese')], max_length=100, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(choices=[('General Works', 'General Works'), ('Philosophy (General) ', 'Philosophy (General) '), ('Auxiliary Sciences of History', 'Auxiliary Sciences of History'), ('History', 'History'), ('History: America', 'History: America'), ('History: America', 'History: America'), ('Geography', 'Geography'), ('Social sciences', 'Social sciences'), ('Political Science', 'Political Science'), ('Law', 'Law'), ('Education', 'Education'), ('Music', 'Music'), ('Fine arts', 'Fine arts'), ('Language and Literature', 'Language and Literature'), ('Science', 'Science'), ('Medicine', 'Medicine'), ('Agriculture', 'Agriculture'), ('Technology', 'Technology'), ('Military Science', 'Military Science'), ('Naval science', 'Naval science'), ('Library Science. Information Resources (General)', 'Library Science. Information Resources (General)')], max_length=100, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='book.Book', verbose_name='Book'),
        ),
    ]
