# Generated by Django 2.2.5 on 2021-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20210520_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Deleted', 'Deleted')], default='Available', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('On-Borrowing', 'On Borrowing'), ('Staff-Only', 'Staff Only'), ('Deleted', 'Deleted')], max_length=100, verbose_name='Status'),
        ),
    ]
