# Generated by Django 2.2.23 on 2021-06-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('rating_number', models.IntegerField(verbose_name='Rating number')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_summary', to='book.Book', verbose_name='Book')),
            ],
            options={
                'db_table': 'library_comment_summary',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.IntegerField(null=True, verbose_name='creator')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modifier', models.IntegerField(null=True, verbose_name='modifier')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('content', models.TextField(max_length=10000, null=True, verbose_name='Content')),
                ('rating', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Rating')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_book', to='book.Book', verbose_name='Book')),
            ],
            options={
                'db_table': 'library_comment',
            },
        ),
    ]
