# Generated by Django 2.2.5 on 2021-05-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsummary',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_summary', to='book.Book', verbose_name='Book'),
        ),
    ]
