# Generated by Django 2.2.23 on 2021-06-10 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20210522_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsummary',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_summary', to='book.Book', verbose_name='Book'),
        ),
    ]
